framework:
    test: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.client:
        alias: Tests\App\Test\Client
    Tests\App\Test\Client:

    Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver:
        class: Tests\FrameworkBundle\Functional\EntityExtension\OverwritableEntityNameResolver
        arguments:
            - "%shopsys.entity_extension.map%"

    Tests\FrameworkBundle\Functional\EntityExtension\OverwritableEntityNameResolver:
        alias: Shopsys\FrameworkBundle\Component\EntityExtension\EntityNameResolver

    Tests\FrameworkBundle\Functional\EntityExtension\OverwritableEntityExtensionSubscriber:
        arguments:
            $entityExtensionMap: '%shopsys.entity_extension.map%'
        tags:
            - { name: doctrine.event_subscriber, priority: -10 }

    Tests\FrameworkBundle\Functional\EntityExtension\EntityExtensionTestHelper: ~

    Symfony\Bridge\Twig\Extension\HttpKernelRuntime:
        arguments: ['@fragment.handler']

    Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

    League\Flysystem\FilesystemOperator:
        alias: 'main_filesystem'

    Tests\FrontendApiBundle\Functional\Payment\GoPay\GoPayClientFactory:
        arguments:
            - '%gopay_config%'

    App\Model\GoPay\GoPayClientFactory:
        alias: Tests\FrontendApiBundle\Functional\Payment\GoPay\GoPayClientFactory

    Symfony\Component\HttpFoundation\RequestStack:
        class: Tests\App\Test\HttpFoundation\RequestStack
        arguments:
            $container: '@test.service_container'
            $requestStack: '@request_stack'
